config/routes.rb
Rails.application.routes.draw do

  resources :apis do
    resources :jsons
  end

  get 'welcome/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

end

app/models/api.rb
require 'securerandom'

class Api < ApplicationRecord
  has_many :jsons, dependent: :destroy
  belongs_to :user

  def self.generate_key
    return SecureRandom.hex(20)
  end

  def self.generate_JSON(params)
    unless params['api-key']
      return JSON.parse('{"message":"No API Key found in headers, body or querystring"}')
    else
      api = Api.where(key: params['api-key'])
      json = api[0].jsons.select {|x| x.name == params['json']}
      return json[0]['content']
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/json.rb
class Json < ApplicationRecord
  belongs_to :api
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :apis, dependent: :destroy
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def index
    unless params['api-key']
      render json: JSON.parse('{"message":"No API Key found in headers, body or querystring"}')
    else
      api = Api.where(key: params['api-key'])
      render json: api[0].jsons.select {|x| x.name == params['json']}
    end
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController

  before_action :allow_requests
  before_action :authenticate_user!, except: [:index]
  before_action :find_by_params, except: [:index, :new, :create]
  before_action :api_owner, except: [:index, :new, :create]


  def index
    render json: Api.generate_JSON(params)
  end

  def new
    @api = Api.new
  end

  def create
    @api = Api.create(api_params)
    @api.key = Api.generate_key
    @api.user_id = current_user.id
    @api.save
    redirect_to '/'
  end

  def show
  end

  def edit
  end

  def update
    @api.name = params[:api][:name]
    if params[:key][:api] == "1"
      @api.key = Api.generate_key
    end
    @api.save
    redirect_to '/'
  end

  def destroy
    @api.destroy
    flash[:notice] = "API successfully deleted"
    redirect_to '/'
  end

  private

  def api_params
    params.require(:api).permit(:name)
  end

  def find_by_params
    @api = Api.find(params[:id])
  end

  def api_owner
    unless @api.user_id == current_user.id
      flash[:notice] = "Permission denied: only owner has access"
      redirect_to '/'
    end
  end

  def allow_requests
    headers['Access-Control-Allow-Origin'] = '*'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jsons_controller.rb
require './lib/json_check'

class JsonsController < ApplicationController

  before_action :find_api_by_params, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :json_owner, except: [:new, :create]

  def new
    @json = Json.new
  end

  def create
    @json = @api.jsons.new(json_params)

    if @json[:content].is_json?
      if unique_title?
        @json.save
        redirect_to api_path(@api)
      else
        flash.now[:alert] = "Name has already been used"
        render :new
      end
    else
      flash.now[:alert] = 'Content is not a valid JSON'
      render :new
    end
  end

  def show
    @json = @api.jsons.find(params[:id])
  end

  def edit
    @json = @api.jsons.find(params[:id])
  end

  def update
    @json = @api.jsons.find(params[:id])
    @json.update(json_params)
    redirect_to api_path(@api)
  end

  def destroy
    @json = @api.jsons.find(params[:id])
    @json.destroy
    flash[:notice] = "JSON successfully deleted"
    redirect_to api_path(@api)
  end

  private

  def json_params
    params.require(:json).permit(:name, :content)
  end

  def find_api_by_params
    @api = Api.find(params[:api_id])

  end

  def json_owner
    unless @api.user_id == current_user.id
      flash[:notice] = "Permission denied: only owner has access"
      redirect_to '/'
    end
  end

  def unique_title?
    @api.jsons.where(name: @json.name).count == 0
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @apis = Api.all
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jsons_helper.rb
module JsonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apis/_jsons-list.html.erb
      <div class="api-title">
        <div class="api-key"> <div id='key'>key</div> <%= @api.key %> </div>
      </div>
      <% if @api.jsons.any? %>
      <div class="jsons-list">
        <% @api.jsons.each do |json| %>
        <div class="api">
          <div class='json-name'>
            <%= link_to json.name, api_json_path(@api,json) %>
          </div>
        </div>

        <% end %>
        <% else %>
        No JSONs yet
      <% end %>
      <br>
      <%= link_to 'Edit API ', edit_api_path(@api) %> |
      <%= link_to ' Delete API', api_path(@api), method: :delete %>
    </div>

app/views/apis/edit.html.erb
<div class="row">
  <div class="col-md-4 header" id='api-list'>Your APIs</div>
  <div class="col-md-8 header" id='json-list'> Create new API</div>

  <% if user_signed_in? %>

  <div class="col-md-12" id="dashboard">
    <%= render partial: "welcome/dashboard" %>

    <div class="col-md-8 dash-column" id="json-list">
      <%= form_for @api, html: {multipart: true} do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :key, 'Refresh API key?' %>
        <%= check_box :key, 'api' %>
        <%= f.submit class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>

  </div>
  <% end %>
  <div class="col-md-4 footer">
    <div id='api-list' class='dash-button'>
      <%= link_to 'add API', new_api_path %>
    </div>
  </div>
  <div class="col-md-8 footer">
    <div id='json-list' class='dash-button'>
    </div>
  </div>

</div>

app/views/apis/new.html.erb
  <div class="row">
    <div class="col-md-4 header" id='api-list'>Your APIs</div>
    <div class="col-md-8 header" id='json-list'> Create new API</div>

    <% if user_signed_in? %>

    <div class="col-md-12" id="dashboard">
      <%= render partial: "welcome/dashboard" %>

    <div class="col-md-8 dash-column" id="json-list">
      <%= form_for @api, html: {multipart: true} do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: 'MyAPI' %>
        <%= f.submit class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>

</div>
<% end %>
  <div class="col-md-4 footer">
    <div id='api-list' class='dash-button'>
      <%= link_to 'add API', new_api_path %>
    </div>
  </div>
    <div class="col-md-8 footer">
      <div id='json-list' class='dash-button'>
    </div>
  </div>

</div>

app/views/apis/show.html.erb
<div class="row">
  <div class="col-md-4 header" id='api-list'>Your APIs</div>
  <div class="col-md-4 header" id='json-list'> JSONS in <%=@api.name %></div>

  <% if user_signed_in? %>

  <div class="col-md-12" id="dashboard">
    <%= render partial: "welcome/dashboard" %>

    <div class="col-md-4 dash-column" id="json-list">
      <%= render "jsons-list" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 footer">
    <div id='api-list' class='dash-button'>
      <%= link_to 'add API', new_api_path %>
    </div>
  </div>
  <div class="col-md-4 footer">
    <div id='json-list' class='dash-button'>
      <%= link_to 'Add JSON', new_api_json_path(@api) %>
    </div>
  </div>
  <% end %>
</div>

app/views/jsons/edit.html.erb
  <div class="row">
    <div class="col-md-4 header" id='api-list'>Your APIs</div>
    <div class="col-md-8 header" id='json-list'> New JSON in <%= @api.name %> </div>

    <% if user_signed_in? %>

    <div class="col-md-12" id="dashboard">
      <%= render partial: "welcome/dashboard" %>

    <div class="col-md-8 dash-column" id="json-list">
    <%= form_for [@api, @json] do |f| %>
    <div class="form-group">
      <div id='name-field'><%= f.label :name %>
      <%= f.text_field :name  %>
    </div>
      <%= f.label :content %>
      <%= f.text_area :content %>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
    <% end %>
    </div>

</div>
<% end %>
  <div class="col-md-4 footer">
    <div id='api-list' class='dash-button'>
      <%= link_to 'add API', new_api_path %>
    </div>
  </div>
    <div class="col-md-8 footer">
      <div id='json-list' class='dash-button'>
    </div>
  </div>

</div>

app/views/jsons/new.html.erb
  <div class="row">
    <div class="col-md-4 header" id='api-list'>Your APIs</div>
    <div class="col-md-8 header" id='json-list'> New JSON in <%= @api.name %> </div>

    <% if user_signed_in? %>

    <div class="col-md-12" id="dashboard">
      <%= render partial: "welcome/dashboard" %>

    <div class="col-md-8 dash-column" id="json-list">
    <%= form_for [@api, @json] do |f| %>
    <div class="form-group">
      <div id='name-field'><%= f.label :name %>
      <%= f.text_field :name, placeholder: 'MyJSON'  %>
    </div>
      <%= f.label :content %>
      <%= f.text_area :content, placeholder: '{"message":"Enter your text as a valid JSON"}'  %>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
    <% end %>
    </div>

</div>
<% end %>
  <div class="col-md-4 footer">
    <div id='api-list' class='dash-button'>
      <%= link_to 'add API', new_api_path %>
    </div>
  </div>
    <div class="col-md-8 footer">
      <div id='json-list' class='dash-button'>
    </div>
  </div>

</div>

app/views/jsons/show.html.erb
  <div class="row">
    <div class="col-md-4 header" id='api-list'>Your APIs</div>
    <div class="col-md-4 header" id='json-list'> JSONS in <%=@api.name %></div>
    <div class="col-md-4 header" id='json-view'> <%= @json.name %> </div>

    <% if user_signed_in? %>

    <div class="col-md-12" id="dashboard">
      <%= render partial: "welcome/dashboard" %>

    <div class="col-md-4 dash-column" id="json-list">
      <%= render partial: "apis/jsons-list" %>
    </div>

    <div class="col-md-4 dash-column" id="json-view">
      <% if @api.jsons.any? %>

        <p>API url: <query class='json-content'>https://spy-api.herokuapp.com/apis?api-key=<%=@api.key%>&json=<%=@json.name%></query></p>
        <br>
          name: <%= @json.name %>
          <div class="json-content">
            content: <%= @json.content %>
          </div>
          <%= link_to 'Delete JSON', api_json_path(@api,@json), method: :delete %>
      <% end %>
    </div>

  <div class="col-md-4 footer"><div id='api-list' class='dash-button'> <%= link_to 'add API', new_api_path %> </div></div>
    <div class="col-md-4 footer">
      <div id='json-list' class='dash-button'>
      <%= link_to 'Add JSON', new_api_json_path(@api) %>
    </div>
  </div>
    <div class="col-md-4 footer">
      <div id='json-view' class='dash-button'>
      <%= link_to 'Edit JSON', edit_api_json_path(@api, @json) %>
    </div>
  </div>
</div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link href="https://fonts.googleapis.com/css?family=Comfortaa|Lato|Open+Sans|Open+Sans+Condensed:300|Poiret+One|Roboto|Ubuntu" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Spy API</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <li class="active"><%= link_to current_user.email, root_path %></li>
            <li class="active"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
          <p class="notice" id='flash'><%= notice %></p>
          <p class="alert" id='flash'><%= alert %></p>
  <div class="row" id='logo'>

    <h1 id="spy-header"> <img src="http://i.imgur.com/YoS29zR.png"/> </h1>
  </div>
        <%= yield %>
      </div>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </body>

</html>

app/views/welcome/_dashboard.html.erb
<div class="col-md-4 dash-column" id="api-list">
<% if current_user.apis.any? %>
  <% current_user.apis.each do |api| %>
  <div class="api">
    <div class="api-name"> <%= link_to api.name, api_path(api) %> </div>
  </div>
  <% end %>
  <% else %>
  <center>No APIs yet!<br>⬇</center>
<% end %>
</div>

app/views/welcome/_introduction.html.erb
<p class="lead">Spy API is a development tool that makes testing your app easier.
  It mocks JSON responses from third party APIs, letting you build your app
  without making endless requests to other sites. Best of all, you decide
  what response you want to get back, so you're never dealing with more
  data than you need.
</p>
  <h3>How it works:</h3>
<ol class="center">
    <li> Sign up for an account</li>
    <li> Generate an API key and upload a JSON</li>
    <li> Make your requests at:
      https://spy-api.herokuapp.com/apis?api-key=YOUR_KEY&json=JSON_NAME</li>

</ol>

app/views/welcome/index.html.erb
  <div class="row">
    <% if user_signed_in? %>
    <div class="col-md-4 header" id='api-list'>Your APIs</div>

    <div class="col-md-12" id="dashboard">
      <%= render "dashboard" %>
    </div>

    <div class="col-md-4 footer"><div id='api-list' class='dash-button'> <%= link_to 'add API', new_api_path %> </div></div>
  <% else %>

    <div id="introduction">
      <%= render "introduction" %>
    </div>

  <% end %>
</div>